# Generated by Django 3.1.4 on 2020-12-12 16:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('Cid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Longitude', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Latitude', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Cityname', models.CharField(max_length=20, unique=True)),
                ('Country', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('Tid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Cid', models.UUIDField(default=uuid.uuid4)),
                ('MaxTemperature', models.DecimalField(decimal_places=1, max_digits=10)),
                ('FromTime', models.DateTimeField()),
                ('ToTime', models.DateTimeField()),
                ('DateTime', models.DateTimeField()),
                ('Date', models.DateField()),
            ],
        ),
    ]
